= ocp-workload-dayinlife

== Role overview

* This is a simple role that does the following:
** Playbook: link:./tasks/pre_workload.yml[pre_workload.yml] - Sets up an
 environment for the workload deployment
*** Adds a user to a list of groups defined in the
 link:./defaults/main.yml[defaults file].
*** Sets a cluster resource quota for the user based on the variables in the
 link:./defaults/main.yml[defaults file] .
*** Debug task will print out: `pre_workload Tasks Complete`

** Playbook: link:./tasks/workload.yml[workload.yml] - Used to deploy the actual
 workload, i.e, 3scale, Mobile or some Demo
*** This role doesn't do anything here
*** Debug task will print out: `workload Tasks Complete`

* This file link:./defaults/main.yml[./defaults/main.yml] contains all the variables you
 need to define to control the deployment of your workload.

NOTE: Check the link:./provision.sh[provision.sh] script to see an example.

=== Importing on ansible_agnostic_deployer manually (while RHPDS is still pending to create the catalog item)

These steps are only needed while RHPDS does not create the catalog item. So you can go there and request your `OpenShift Workshop` from the catalog.

* Clone this link:https://github.com/sborenst/ansible_agnostic_deployer.git[repo] and create a folder called `ocp-workload-dayinlife` on `ansible_agnostic_deployer/ansible/roles`.
* Copy the content from this folder `support` tho the folder you just created in the previous step.
* Move to the `ansible_agnostic_deployer/ansible` and create your own `provision.sh` script.

NOTE: Check the link:./provision.sh[provision.sh] script to see an example.


=== Deploy a Workload with the `ocp-workload` playbook [Mostly for testing]
----
TARGET_HOST="bastion.dev39.openshift.opentlc.com"
OCP_USERNAME="opentlc-mgr"
WORKLOAD="ocp-workload-dayinlife"
GUID=0878
OCP_DOMAIN="dev39.openshift.opentlc.com"
TOKEN=$(oc whoami -t)



# a TARGET_HOST is specified in the command line, without using an inventory file
ansible-playbook --become --become-user=${OCP_USERNAME}, ./configs/ocp-workloads/ocp-workload.yml \
                 -e"ansible_ssh_private_key_file=~/.ssh/id_rsa" \
                 -e"ansible_ssh_user=ec2-user" \
                 -e"ANSIBLE_REPO_PATH=`pwd`" \
                 -e"ocp_username=${OCP_USERNAME}" \
                 -e"ocp_workload=${WORKLOAD}" \
                 -e"guid=${GUID}" \
                 -e"ocp_user_needs_quota=true" \
                 -e"ocp_domain=${OCP_DOMAIN}" \
                 -e"ocp_apps_domain=apps.${OCP_DOMAIN}" \
                 -e"openshift_oauth_token=${TOKEN}" \
                 -e"ACTION=create"

----

=== To Delete an environment
----
TARGET_HOST="bastion.rhpds.openshift.opentlc.com"
OCP_USERNAME="hchin-redhat.com"
WORKLOAD="ocp-workload-fuse-ignite"
GUID=3005

# a TARGET_HOST is specified in the command line, without using an inventory file
ansible-playbook -i ${TARGET_HOST}, ./configs/ocp-workloads/ocp-workload.yml \
                 -e"ansible_ssh_private_key_file=~/.ssh/id_rsa" \
                    -e"ansible_ssh_user=opentlc-mgr" \
                    -e"ANSIBLE_REPO_PATH=`pwd`" \
                    -e"ocp_username=${OCP_USERNAME}" \
                    -e"ocp_workload=${WORKLOAD}" \
                    -e"guid=${GUID}" \
                    -e"ACTION=remove"
----
