package com.redhat;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-09-28T10:26:33.540-04:00
 * Generated source version: 3.2.6
 *
 */
@WebServiceClient(name = "LocationDetailService",
                  wsdlLocation = "http://localhost:8080/ws/location?wsdl",
                  targetNamespace = "http://redhat.com/")
public class LocationDetailService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://redhat.com/", "LocationDetailService");
    public final static QName LocationDetailServicePort = new QName("http://redhat.com/", "LocationDetailServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/ws/location?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(LocationDetailService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/ws/location?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public LocationDetailService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public LocationDetailService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LocationDetailService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public LocationDetailService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public LocationDetailService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public LocationDetailService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns LocationDetailServicePortType
     */
    @WebEndpoint(name = "LocationDetailServicePort")
    public LocationDetailServicePortType getLocationDetailServicePort() {
        return super.getPort(LocationDetailServicePort, LocationDetailServicePortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LocationDetailServicePortType
     */
    @WebEndpoint(name = "LocationDetailServicePort")
    public LocationDetailServicePortType getLocationDetailServicePort(WebServiceFeature... features) {
        return super.getPort(LocationDetailServicePort, LocationDetailServicePortType.class, features);
    }

}
